version: '3.8'

services:
  app:
    build: .
    container_name: dockerized-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
